server:
  port:
    8083

dao:
  test:
    name: godv

    # mybatisplus代码生成器配置
generator:
  username: root
  password: dyw5211314
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/godv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  dbTableList: #数据库的表，可多张(自己设置)

  prefix:

datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/godv?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
  username: root
  password: dyw5211314
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 5
    maximum-pool-size: 100
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1