spring:
  application:
    name: godv-lgd #服务名称
  servlet:
    multipart:
      #附件最大限制
      max-file-size: 100MB
      max-request-size: 1000MB
  #激活哪一个环境的配置文件
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true



dao:
  test:
    name: godv

