spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1662491739tnpow.mysql.rds.aliyuncs.com:3306/qingtianbak?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: qingtian
    password: passw0rdHZ
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.qingtian-dev.svc.cluster.local:8848
        enabled: true
        register-enabled: true
        namespace: da814842-135c-4d28-8ef0-83afdcf72c8f
        service: api-service

  #  redis:
  #    cluster:
  #      nodes: r-bp1i8onxsjzhino5x3.redis.rds.aliyuncs.com:6379
  #      password: rvdjhG6lAG%En*fX
  #      max-redirects: 3
  #      timeout: 1000
  redis:
    host: r-bp1i8onxsjzhino5x3.redis.rds.aliyuncs.com  #redis服务器地址
    port: 6379   #redis服务器连接端口
    password: rvdjhG6lAG%En*fX   #密码（默认为空）
    database: 0  #数据库索引（默认为0）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接 
        min-idle: 0    # 连接池中的最小空闲连接
    timeout: 5000s
txp:
  itemTag: P88SPGhhPGvLMG9-OFleMgTT
  getOrderInfoUrl: https://eco.taobao.com/router/rest
  ignoreInvitorId: MGIuvGgYvmMIMF7-O8Q0PkcYP8PzOFx0P8P-X8kWMHxT
  groupEncryptItemTag: MHQYPGP-X8*eXFk4MkZzvNTT # 团购商品标签

base:
  domain: h5.qingtian.qibcms.com #h5平台域名（和商家配置域名区分开）

# rocketmq  配置
rocketmq:
  accessKey: LTAI4Fh1tbNTLDjQgSxVmwJg
  secretKey: VI5A40EFwXvlReVNB53aRp9boGDWK6
  nameSrvAddr: http://MQ_INST_1383765569391052_BXVGnlXS.cn-hangzhou.mq-internal.aliyuncs.com:8080
  delayTopic: qtDelayDev
  delayGroupId: GID-QBY-FM-QT
  delayTag: declarDelay
  activeTag: activeDelay
  orderTopic: ssOrder
  orderGroupId: GID-QBY-FM-SS-ORDER
  commonTopic: ssCommon
  commonGroupId: GID-QBY-FM-SS-COMMON
#  orderTags: goods_msg_tag || order_msg_tag || bind_msg_tag || addCompany || companySign || userSign || singlePay || orig_order_msg_tag || orig_user_msg_tag


#小程序appId和secret(擎天结算测试)
miniProgram:
  appId: wx655e394769500d16
  secret: f39ec4ef678e127615e8fe523be83653

#小程序appId和secret(擎天报单测试)
declareMiniProgram:
  appId: wx7ec002e43a400261
  secret: f92d7a67ffdd16cacc7a1ba58fd233bb

#好货邦公众号appId和appSecret
wechatGzh:
  appId: wxb5b2a91c404ae3c8
  appSecret: 67abaa075d7e7e0758cc0faa27b09e3b

#调用淘小铺推送邀请地址
tmallshop:
  serverUrl: http://gw.api.taobao.com/router/rest   # 线上环境的地址
  # serverUrl: http://pre-gw.api.taobao.com/top/router/rest   # 预发联调的地址
  collectionServerUrl:  http://pre-gw.api.taobao.com/top/router/rest #集单功能预发联调地址
  apiInvitorUrl: taobao.spire.organization.pricediff.invite # 邀请关系发送至淘小铺接口地址
  apiSimInvitorUrl: taobao.spire.organization.pricediff.invitebymobile # 邀请关系发送淘小铺，手机号的方式
  periodUrl: taobao.spire.organization.pricediff.item.period # 淘小铺价差机构商品排期接口地址
  detailUrl: taobao.spire.organization.pricediff.item.detail # 淘小铺价差机构查询商品详情信息接口地址
  materialUrl: taobao.spire.organization.pricediff.item.material # 淘小铺价差机构查看商品素材接口地址
  collectionUrl: taobao.spire.organization.pricediff.item.material # 淘小铺价差机构同步集单数据
  appkey: 32204294
  appSecret: a2a9d851a5ff40c3dc6dbd9982536971
  sessionKey: 620232682c5907b174a0d1a78521ceb6a9ZZc5183124d102115787017
  #淘小铺的线上测试数据，需排除
  txpData: 1328265318442733570,1328278831185793026,1337065043693465601,1348510139395284993,1341999247393636353,1355449949991190530,1354003071080198146,1354682438169632770,1354688889041661953,1354692965773938689,1356065734094479361,1356176327824711682,1354274801377402881,1347625394813739009,1356176327824711682,1362580015935057922,1356176327824711682,1356065734094479361,1354692965773938689,1354688889041661953,1354682438169632770,1354274801377402881,1348510139395284993,1347625394813739009,1344175198848364545,1341999247393636353,1337065043693465601
  #txpData: 1350018261566029826,1340891913829302274
  #淘小铺往后拉取商品天数配置
  days: 4
  #淘小铺往前拉取商品天数配置
  beforeDays: 3
  simpFlowSwitch: 2 # 邀请注册简化流程开关   0是关；2是开
  pushModInvitorInfoToSmallShopUrl: https://xpt-japi-svc:8013/api/modify/invite/relation

# 快递查询
express:
  appKey: 500005
  secret: EtqeseeMrfNi3dpst6eNE3z3oiMA7WXV
  url: http://sms.tmallshop.cn

#环境标识
envFlag: test

#税优
fax:
  name: 中僖税优服务协议
  channelCode: zx
  custContractUrl: https://qbqingtian.oss-cn-hangzhou.aliyuncs.com/file/acp/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%8E%92%E6%9F%A5.pdf
  userContractUrl: https://qbqingtian.oss-cn-hangzhou.aliyuncs.com/file/acp/%E7%94%B5%E5%AD%90%E9%9D%A2%E5%8D%95%E6%8E%92%E6%9F%A5.pdf
  baseUrl: http://faxapi.qingtian.qibcms.com/
  invoiceType: 1

#微信开放平台第三方平台
wechatOpen:
  #擎天智能结算 测试环境用
  appid: "wxda3c51978438cf6a"
  token: "e71c71f0bf1c49ab913c939194b1d275"
  encodingAesKey: "rzoRlZV9cHOYf1HKU3lHKIitRBXx0jx7iuYce9TK7RC"
  #todo 第三方平台的APPSECRET
  appsecret: "2ad307d37e3aab64db0128fafb18ca76"

#微信地址调用
wx:
  #微信授权获取openId
  authUrl: https://api.weixin.qq.com/sns/jscode2session?appid=APPID&secret=SECRET&js_code=JSCODE&grant_type=authorization_code



dingding:
  sendMessage: false

mp:
  appkey: 324565473
  secret: sec32fss
  url: gateway.qingtian.qibosys.com/settle

#微分销对接接口url地址
wfx:
  interfaceUrl: http://dts.wfx.wxfenxiao.com/

xxl:
  job:
    accessToken:
    admin:
      addresses: http://xxljob-svc:8080/xxl-job-admin
    executor:
      appname: ${spring.application.name}-${spring.profiles.active}
      ip:
      port: 8911
      logretentiondays: 1


isCommission:
  #shopId之间用逗号隔开
  shopIds: 1391949698312740865